version: '3.1'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_SERVER_PORT: 80
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - web
  web:
    build: .
    environment:
      NODE_ENV: development
      PORT: 80
      mongo_url: mongodb://mongo:27017
      mongo_db: speak-langs

      google_clientID: 1012351264239-rn254nbkr9jm9q786t563odp3n7uuf59.apps.googleusercontent.com
      google_clientSecret: GD_HWtyDsQ1fweR4aPDQ40_t
      google_callbackURL: http://speak-langs.com/auth/google/oauth2callback

      baidu_clientID: pOkGhm4bG5D5fdnZHb9iNttX
      baidu_clientSecret: dOecNbfLOY5IgRoFQEAVzZ1Y2WGrbvtl
      baidu_callbackURL: http://speak-langs.com/auth/baidu/oauth2callback

      weibo_clientID: 3350792186
      weibo_clientSecret: 716743af54404037d82b4bedc1d99aa3
      weibo_callbackURL: http://speak-langs.com/auth/weibo/oauth2callback
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: zetsin
      ME_CONFIG_BASICAUTH_PASSWORD: zetsin
    depends_on:
      - mongo
      