version: '3.1'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      REACT_APP_SERVER_PORT: 80
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - web
  web:
    build: .
    environment:
      NODE_ENV: development
      PORT: 80
      mongo_url: mongodb://mongo:27017
      mongo_db: speak-langs

      google_clientID: 'clientID'
      google_clientSecret: 'clientSecret'
      google_callbackURL: http://speak-langs.com/auth/google/oauth2callback

      baidu_clientID: 'clientID'
      baidu_clientSecret: 'clientSecret'
      baidu_callbackURL: http://speak-langs.com/auth/baidu/oauth2callback

      weibo_clientID: 'clientID'
      weibo_clientSecret: 'clientSecret'
      weibo_callbackURL: http://speak-langs.com/auth/weibo/oauth2callback
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo
      