version: '3.1'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - web
  web:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
      